# Generated by Django 3.1 on 2023-08-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('AP', 'Aperfeiçoamento'), ('CP', 'Capacitação'), ('OF', 'Oficina'), ('TR', 'Treinamento')], max_length=2)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ementa', models.TextField()),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porcentagem_teoria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentagem_pratica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('numero_matricula', models.CharField(max_length=9)),
                ('data_matricula', models.DateField()),
                ('aluno_especial', models.BooleanField(default=False)),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('numero_funcionario', models.CharField(max_length=9)),
                ('data_contratacao', models.DateField()),
                ('dedicacao_exclusiva', models.BooleanField()),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horario', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Ministrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministrante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ministrante')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.aluno')),
            ],
        ),
    ]
